// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcbqYgeIflUCVvPi3S4rJE_CZfwE6FvN8',
    appId: '1:493909601017:web:12c3e71f40d91b812d1028',
    messagingSenderId: '493909601017',
    projectId: 'royaltaxibeta',
    authDomain: 'royaltaxibeta.firebaseapp.com',
    storageBucket: 'royaltaxibeta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdgW6_7x8GHGvQQU8YdIB-c39mfAD2NFE',
    appId: '1:493909601017:android:780f8802197994002d1028',
    messagingSenderId: '493909601017',
    projectId: 'royaltaxibeta',
    storageBucket: 'royaltaxibeta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGv9SWqBrnYXbR1eH1QMlErqrP93g2wRM',
    appId: '1:493909601017:ios:6b15a18e212fc2762d1028',
    messagingSenderId: '493909601017',
    projectId: 'royaltaxibeta',
    storageBucket: 'royaltaxibeta.appspot.com',
    iosBundleId: 'com.milleniumhz.royalTaxiBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGv9SWqBrnYXbR1eH1QMlErqrP93g2wRM',
    appId: '1:493909601017:ios:6b15a18e212fc2762d1028',
    messagingSenderId: '493909601017',
    projectId: 'royaltaxibeta',
    storageBucket: 'royaltaxibeta.appspot.com',
    iosBundleId: 'com.milleniumhz.royalTaxiBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcbqYgeIflUCVvPi3S4rJE_CZfwE6FvN8',
    appId: '1:493909601017:web:90011fbe859fc1b22d1028',
    messagingSenderId: '493909601017',
    projectId: 'royaltaxibeta',
    authDomain: 'royaltaxibeta.firebaseapp.com',
    storageBucket: 'royaltaxibeta.appspot.com',
  );
}
